name: Release

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

jobs:
  release:
    strategy:
      matrix:
        node-version: [18.x]

    name: Create a new release
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'imbhargav5/nextbase-nextjs13-supabase-starter'}}
    steps:
      - name: 🚂 CI Setup
        uses: ./.github/actions/ci-setup
      - name: ⚛️ Install packages
        uses: ./.github/actions/install-packages
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn semantic-release
